Month 7/step 2
neh0chy/react-burger pull request #2
Opened 2022-12-07 03:20 UTC by neh0chy

2022-12-07 06:46 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Теперь ингредиенты приходят от сервера;

- В приложении есть модальные окна;

### **Но есть несколько замечаний, которые нужно исправить (В основном замечания отмечены в коде):**

- В хедере, активна должна быть только первая ссылка. https://yadi.sk/d/H--sAPwAHHcyuw

- Исправьте замечание по propTypes, отметил места в коде.

### **Сделает код лучше:**

- используйте деструктуризацию в пропсах.

- при клике на таб скролить список ингредиентов к нужному разделу.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-07 06:46 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +      .then(data => setData(data['data']))
**Можно лучше:**

Лучше написать так: 

```js
.then(res => setData(res.data))
```

2022-12-07 06:46 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +    const api = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`.

имена констант принято записывать в стиле UPPER_CASE.

2022-12-07 06:46 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +    fetch(api)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-12-07 06:46 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const mainFilter = props.data.filter((item) => item.type === "main");
**Можно лучше:**

Лучше обернуть в `useMemo`, чтобы не было повторных фильтраций, при ререндере.

2022-12-07 06:46 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        <IngredientDetails data={ingredient}></IngredientDetails>
**Можно лучше:**

Похожее замечание есть в `burger-constructor`.

2022-12-07 06:46 UTC, ArslanDev666 commented on src/utils/types.jsx
> +export const propTypesList = PropTypes.shape({
**Можно лучше:**

Лучше переименовть в `ingredientType`

2022-12-07 06:46 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +};
**Надо исправить:**

Описаны не те пропсы, которые используются в компоненте.

2022-12-07 06:46 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.jsx
> +};
**Надо исправить:**

Аналогичное замечание в компоненте `modal`

2022-12-07 06:46 UTC, ArslanDev666 commented on src/utils/types.jsx
> +import PropTypes from 'prop-types';
**Надо исправить:**

расширение у этого файла должно быть просто `.js`, а не `.jsx`. Здесь ведь не используется `jsx`.

2022-12-07 10:51 UTC, neh0chy commented on src/components/app/app.jsx
> +        <BurgerConstructor data={serverDataConstructor}/>
Добрый день. А по заданию нигде не сказано, что в конструкторе данные должны быть с сервера, я возможно не понял, но сейчас там захардкоженные данные просто для красивой вёрстки сделаны, чтобы впоследствии туда добавлять самостоятельно ингредиенты

2022-12-07 16:30 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены.

### **Но есть замечания, которые нужно исправить:**

- Отметил пару маленьких замечаний в коде.

### **Сделает код лучше:**

- Контент по центру, а вот хедер не очень) https://yadi.sk/d/6oupRSw0hIaSMw

- при клике на таб скролить список ингредиентов к нужному разделу.

2022-12-07 16:30 UTC, ArslanDev666 commented on src/utils/burger-api.js
> +    .catch(err => console.log(`Error: ${err}`));
**Можно лучше:**

если вы тут оставите этот лог, то он только тут и вызовется, вам нужно генерировать ошибку `throw new Error("Текст ошибки").`

2022-12-07 16:30 UTC, ArslanDev666 commented on src/components/burger-ingredient/burger-ingredient.jsx
> +};
**Надо исправить:**

Описаны не те пропсы, которые используются в компоненте, также не забывайте про `.isRequired`.

2022-12-07 16:30 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +  // const bun = useMemo(() => props.data.filter((item) => item.type === 'bun'), [props.data]);
**Надо исправить:**

У вас правильно было)) единственное что, используйте метод `find`, а не фильтр.

2022-12-07 16:30 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +          />
**Надо исправить:**

Подставьте сюда, и ниже - данные из `bun`) главное не забудьте, что у нас есть приписка `(верх)` и `(низ)`

2022-12-07 16:30 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.jsx
> +ModalOverlay.propTypes = {
**Надо исправить:**

Не забывайте указывать `.isRequired`, без этого пропсы не будут проверяться.

2022-12-08 07:44 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята🔥, Удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

2022-12-19 00:02 UTC, merged